// component list path; ../react-native/Libraries/react-native/react-native-implementation.js
import {
    AccessibilityInfo,
    ActivityIndicator,
    ART,
    Button,
    CheckBox,
    DatePickerIOS,
    DrawerLayoutAndroid,
    FlatList,
    Image,
    ImageBackground,
    ImageEditor,
    ImageStore,
    KeyboardAvoidingView,
    ListView,
    MaskedViewIOS,
    Modal,
    NavigatorIOS,
    Picker,
    PickerIOS,
    ProgressBarAndroid,
    ProgressViewIOS,
    SafeAreaView,
    ScrollView,
    SectionList,
    SegmentedControlIOS,
    Slider,
    SnapshotViewIOS,
    Switch,
    RefreshControl,
    StatusBar,
    SwipeableFlatList,
    SwipeableListView,
    TabBarIOS,
    Text,
    TextInput,
    ToastAndroid,
    ToolbarAndroid,
    Touchable,
    TouchableHighlight,
    TouchableNativeFeedback,
    TouchableOpacity,
    TouchableWithoutFeedback,
    View,
    ViewPagerAndroid,
    VirtualizedList,
    WebView,


} from 'react-native';

import {
    // APIs
    ActionSheetIOS,
    Alert,
    AlertIOS,
    Animated,
    AppRegistry,
    AppState,
    AsyncStorage,
    BackAndroid, // deprecated: use BackHandler instead
    BackHandler,
    CameraRoll,
    Clipboard,
    DatePickerAndroid,
    DeviceInfo,
    Dimensions,
    Easing,
    findNodeHandle,
    I18nManager,
    ImagePickerIOS,
    InteractionManager,
    Keyboard,
    LayoutAnimation,
    Linking,
    NativeEventEmitter,
    NetInfo,
    PanResponder,
    PermissionsAndroid,
    PixelRatio,
    // PushNotificationIOS,
    Settings,
    Share,
    StatusBarIOS,
    StyleSheet,
    Systrace,
    TimePickerAndroid,
    TVEventHandler,
    UIManager,
    unstable_batchedUpdates,
    Vibration,
    VibrationIOS,

    // Plugins
    DeviceEventEmitter,
    NativeAppEventEmitter,
    NativeModules,
    Platform,
    processColor,
    requireNativeComponent,
    takeSnapshot,

    // Prop Types
    ColorPropType,
    EdgeInsetsPropType,
    PointPropType,
    ViewPropTypes,

    // Deprecated
    Navigator
} from 'react-native'

import { packComponentsPropStyle } from './index'

const cs = packComponentsPropStyle({
    AccessibilityInfo,
    ActivityIndicator,
    ART,
    Button,
    CheckBox,
    DatePickerIOS,
    DrawerLayoutAndroid,
    FlatList,
    Image,
    ImageBackground,
    ImageEditor,
    ImageStore,
    KeyboardAvoidingView,
    ListView,
    MaskedViewIOS,
    Modal,
    NavigatorIOS,
    Picker,
    PickerIOS,
    ProgressBarAndroid,
    ProgressViewIOS,
    SafeAreaView,
    ScrollView,
    SectionList,
    SegmentedControlIOS,
    Slider,
    SnapshotViewIOS,
    Switch,
    RefreshControl,
    StatusBar,
    SwipeableFlatList,
    SwipeableListView,
    TabBarIOS,
    Text,
    TextInput,
    ToastAndroid,
    ToolbarAndroid,
    Touchable,
    TouchableHighlight,
    TouchableNativeFeedback,
    TouchableOpacity,
    TouchableWithoutFeedback,
    View,
    ViewPagerAndroid,
    VirtualizedList,
    WebView
}, {});
module.exports = {
    ...cs,
    // APIs
    ActionSheetIOS,
    Alert,
    AlertIOS,
    Animated,
    AppRegistry,
    AppState,
    AsyncStorage,
    BackAndroid, // deprecated: use BackHandler instead
    BackHandler,
    CameraRoll,
    Clipboard,
    DatePickerAndroid,
    DeviceInfo,
    Dimensions,
    Easing,
    findNodeHandle,
    I18nManager,
    ImagePickerIOS,
    InteractionManager,
    Keyboard,
    LayoutAnimation,
    Linking,
    NativeEventEmitter,
    NetInfo,
    PanResponder,
    PermissionsAndroid,
    PixelRatio,
    // PushNotificationIOS,
    Settings,
    Share,
    StatusBarIOS,
    StyleSheet,
    Systrace,
    TimePickerAndroid,
    TVEventHandler,
    UIManager,
    unstable_batchedUpdates,
    Vibration,
    VibrationIOS,

    // Plugins
    DeviceEventEmitter,
    NativeAppEventEmitter,
    NativeModules,
    Platform,
    processColor,
    requireNativeComponent,
    takeSnapshot,

    // Prop Types
    ColorPropType,
    EdgeInsetsPropType,
    PointPropType,
    ViewPropTypes,

}